name: Linting

on:
  pull_request:
    branches: [ main, master ]

jobs:
  luacheck:
    name: Lua Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Install Lua and Luacheck
        run: |
          make install

      - name: Run Luacheck
        run: |
          make lint
